apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vl2adgabh-nodejs-gitops
  description: This is GitOps manifest for vl2adgabh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: vl2adgabh-nodejs
    jenkins.io/job-full-name: vl2adgabh-nodejs-gitops
    backstage.io/kubernetes-id: vl2adgabh-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vl2adgabh-nodejs
